### ISSUE TITLE
How to reset  "incremental numeric IDs"

### ISSUE THREAD

**Issue by NextReworks** [Sintropiadotio/orma#1]
i'm try to delete  or reset  the PropertiesService, but  it is not working.
can you help me please

**Comment by Sintropiadotio** [comment]
Thankyou NextReworks,

As you can see in the CHANGELOG.md we have now released the Version 9.
With this version you can now access to 2 new functions: 
getProperties & deleteProperty.

With the ORMA.getProperties() method you can now get an array of the keys of the properties saved in the AppsScript PropertiesService

With the ORMA. deleteProperty(propertyKey) method you can delete a property of the properties saved in the AppsScript PropertiesService.

You can find more details in the README.md
